/**
 * Runtime access to the deployed checkpoint version used by the
 * /api/trpc/app-version endpoint (client cache busting).
 *
 * - Development: reads client/public/__manus__/version.json at runtime
 *   (written by the platform), or returns "unknown".
 * - Production: the Vite build plugin overwrites this file at build time with
 *   the version baked from client/public/__manus__/version.json, so no file
 *   reads are needed — client/public is not shipped to the production
 *   container. The generated export takes precedence in both cases.
 */
import fs from "node:fs";
import path from "node:path";

const AUTOGENERATED_MARKER = "AUTOGENERATED_BUILD_VERSION";

// `GENERATED_VERSION` is replaced in place by vitePluginBuildVersionMarker
// during `vite build` (default "unknown").
export const GENERATED_VERSION: string = "27fbd4c9";

export function readBuildVersion(): string {
  // Prefer the build-time value when it was actually generated; otherwise
  // fall back to a runtime read (development).
  if (GENERATED_VERSION !== "unknown") {
    return GENERATED_VERSION;
  }
  try {
    const versionJsonPath = path.resolve(
      import.meta.dirname,
      "..",
      "..",
      "client",
      "public",
      "__manus__",
      "version.json"
    );
    if (fs.existsSync(versionJsonPath)) {
      const published = JSON.parse(
        fs.readFileSync(versionJsonPath, "utf8")
      ) as { version?: string };
      if (typeof published.version === "string") {
        return published.version;
      }
    }
  } catch {
    // Fall through to "unknown".
  }
  return "unknown";
}
