// Exposes the deployed checkpoint version so the client cache-busting logic
// can compare the build-embedded marker against the server-published version
// and force a hard reload on mismatch (mobile browsers such as Brave/Android
// aggressively cache stale JS/CSS bundles). Production hosting rewrites
// non-/api paths to the SPA index.html, so this lives on an Express route
// rather than a static file.
//
// The version is baked into the server bundle at build time: the Vite build
// plugin reads client/public/__manus__/version.json and generates
// server/_core/buildVersion.ts (generated by vitePluginBuildVersionMarker),
// which esbuild inlines into dist/index.js. No runtime file reads are needed,
// which keeps this reliable in production where client/public is not shipped
// to the container.

import express, { type Express, type Router, type Request, type Response } from "express";
import { readBuildVersion } from "./_core/buildVersion";

// The deployed version is resolved at runtime from the build-generated module
// server/_core/buildVersion.ts (written by vitePluginBuildVersionMarker at
// build time). "unknown" is used when the build could not determine a
// published version. The module is imported through a dedicated file so that
// in development the dev server (tsx watch server/_core/index.ts) can serve
// the same API while the generated module exists alongside it.
export function getBuildVersion(): string {
  return readBuildVersion();
}

export function registerAppVersionRoute(app: Express | Router) {
  // The version endpoint lives inside the proxied /api/trpc path space:
  // production hosting only forwards /api/trpc (and /api/oauth) to the Express
  // server, rewriting all other paths to the SPA index.html. The handler is
  // registered on the sub-router mounted at "/api/trpc" BEFORE the tRPC
  // middleware so it wins over tRPC's catch-all sub-path handling, with a
  // route path relative to the mount point.
  (app as Router).get("/app-version", (_req: Request, res: Response) => {
    res.type("json").send({ version: getBuildVersion() });
  });
}
